apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prpr-100
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prprpr
  source:
    repoURL: https://github.com/carlosaya/demo-web-app
    targetRevision: HEAD
    path: helm/demo-web-app
    helm:
       values: |
          version: 1.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: pr-100
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true