apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prprpr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: 'prprpr'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'apps/demo-web-app/helm'
    repoURL: 'https://github.com/grant-lawton-dragonfly/gai-hackathon/'
    targetRevision: HEAD
  project: prprpr
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
