apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prprpr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: prprpr
  source:
    repoURL: https://github.com/carlosaya/demo-web-app.git
    targetRevision: HEAD
    path: helm/demo-web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: prprpr
